import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import PushNotificationProvider from "@/components/PushNotificationProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <PushNotificationProvider>
            <div
              className="bg-cover bg-center min-h-screen"
              style={{
                backgroundImage:
                  "url('https://image.slidesdocs.com/responsive-images/background/blue-white-leaf-outdoor-sunny-rural-cartoon-beautiful-powerpoint-background_9a81889e57__960_540.jpg')",
              }}
            >
              {children}
            </div>
          </PushNotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
